Work
a-kanteruk/Advanced_Java pull request #1
Opened 2023-03-27 14:14 UTC by a-kanteruk

2023-03-27 19:00 UTC, MVlasovD requested changes
Пока так

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/Animal.java
> +        Dog dog = new Dog("Spike", 40);
```suggestion
        Animal dog = new Dog("Spike", 40);
```

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/Animal.java
> +        Cat cat = new Cat("Luci", 6);
```suggestion
        Animal cat = new Cat("Luci", 6);
```

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/BracketValidation.java
> +    private static boolean bracketValidation(String userMessage){
У тебя проверка основана на подсчете скобок, но если перво скобкой будет закрывающаяся скобка?

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/CountTwo.java
> +    private static void myCount(int userNumber){
Название метода не по конвенции

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/CharEquals.java
> +    private static Map myEquals(String userMessage){
Название метода не по конвенции

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/BracketValidation.java
> +    private static boolean bracketValidation(String userMessage){
```suggestion
    private static boolean isBracketsValid(String userMessage){
```

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/BracketInsertion.java
> +    private static void bracketInsertion(String someMessage) {
```suggestion
    private static void insertBrackets(String someMessage) {
```

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/CharEquals.java
> +public class CharEquals {
Я не понял какое это задание

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/CountTwo.java
> +        Integer num;
Используешь то ссылочный интежер, то примитив

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/CountTwo.java
> +            for (Character j: str.toCharArray()){
Задача не понята

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/MaxRecurringSymbol.java
> +    private static Character maxRecurringSymbol(String userMessage){
Название метода не по конвенции

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/MyIterator.java
> +    public void myIterator(int[] someArray){
Название метода

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/StringCompression.java
> +    private static String myCompressor(String userMessage){
Название метода

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/UniqueList.java
> +    public List uniqueElements(List someCollections){
Название метода

2023-03-27 19:00 UTC, MVlasovD commented on src/main/java/net/dunice/UniqueList.java
> +
Необходимо написать метод, который принимает любую коллекцию и возвращает ее без дубликатов

2023-03-27 19:11 UTC, a-kanteruk commented on src/main/java/net/dunice/BracketValidation.java
> +    private static boolean bracketValidation(String userMessage){
Если будет первая скобка закрывающаяся, то цикл проверки прервется и будет выдано false.

2023-03-30 14:50 UTC, MVlasovD requested changes

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/Animal.java
> +
строка

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/Animal.java
> +
лишняя строка

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/CountTwo.java
> +    private static void countNumber(int userNumber){
почему ты везде используешь статичные методы?
для разнообразия сделал бы какую-нибудь задачу, не используя их

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/IdenticalPairs.java
> +        int[] myArray = {1, 2, 3, 3, 3, 4, 5, 6, 2, 4, 5};
в логике есть проблемы, считает пары не верно
```suggestion
        int[] myArray = {1, 2, 3, 3, 3, 4, 5, 6, 2, 4, 5};
```
здесь пар больше, чем приложение считает (здесь их вроде 6 пар)

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/MaxRecurringSymbol.java
> +        Map<Character,Integer> messageMap = new HashMap();
некорректно работает
при вводе  ffaass 
Самый повторяющийся символ - a
хотя это f 

попробуй так 
```suggestion
        Map<Character,Integer> messageMap = new LinkedHashMap();
```

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/SpaceCompression.java
> +
строка

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/StringCompression.java
> +    private static String compressString(String userMessage){
немного работает не по требованиям к задаче

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/EmployersComparator.java
> +        employersList.stream().sorted().forEach(System.out::println);
для стримов используется иная синтаксическая запись, их принято записывать иначе
поправь везде

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/EmployersComparator.java
> +        employersList.stream().filter(employer -> employer.getSalary() > 100000).forEach(System.out::println);
employer это работодатель))

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/EmployersComparator.java
> +class Employer implements Comparable<Employer>{
```suggestion
class Employee implements Comparable<Employee>{
```

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/EmployersComparator.java
> +    public int compare(Employer employer1, Employer employer2) {
переопределенный метод compare можно написать по другому

 public int compare(Employer employer1, Employer employer2) {
return employer1.getTermOfService() - employer2.getTermOfService();
}

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/EmployersComparator.java
> +class SortBySalary implements Comparator<Employer>{
```suggestion
class SortBySalary implements Comparator<Employee>{
```

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/EmployersComparator.java
> +class SortByAge implements Comparator<Employer>{
```suggestion
class SortByAge implements Comparator<Employee>{
```

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/EmployersComparator.java
> +        Map<String, List<Employer>> myEmployers = employersList.stream()
любишь мапу))

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/EmployersComparator.java
> +        double averageSalary = employersList.stream().collect(Collectors.averagingInt(Employer::getSalary));
```suggestion
        double averageSalary = employersList
        .stream()
        .collect(Collectors.averagingInt(Employer::getSalary));
```

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/StreamStudents.java
> +class Students{
используй ломбок

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/EmployersComparator.java
> +    private String name;
используй ломбок

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/StreamStrings.java
> +        myList.stream().sorted().forEach(System.out::println);
```suggestion
        myList.stream()
        .sorted()
        .forEach(System.out::println);
```

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/StreamStrings.java
> +        myList.stream().map(item -> item + "_1").forEach(System.out::println);
запись стрима

2023-03-30 14:50 UTC, MVlasovD commented on src/main/java/net/dunice/StreamStrings.java
> +        int[] myArray = myList.stream().map(item -> item.replace("a",""))
запись стрима

2023-03-31 07:55 UTC, MVlasovD approved these changes

2023-03-31 07:55 UTC, MVlasovD commented on src/main/java/net/dunice/EmployeesComparator.java
> +        employersList.add(new Employee("Genry",28,80000, 1));
```suggestion
        employeesList.add(new Employee("Genry",28,80000, 1));
```

2023-03-31 08:16 UTC, merged